name: Fetch Conjur Secret

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl and jq
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Authenticate to Conjur and retrieve secret
        env:
          CONJUR_ACCOUNT: conjur
          CONJUR_APPLIANCE_URL: ${{ secrets.CONJUR_APPLIANCE_URL }}
          CONJUR_AUTHN_LOGIN: ${{ secrets.CONJUR_AUTHN_LOGIN }}
          CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}
        run: |
          set -e
          echo "Logging into Conjur..."
          FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            --request POST \
            --data "$CONJUR_API_KEY" \
            "$FULL_AUTHN_URL")
          BODY=$(echo "$RESPONSE" | sed '$d')
          STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
          if [ "$STATUS_CODE" != "200" ]; then
            echo "Authentication failed"
            echo "$BODY"
            exit 1
          fi
          AUTHN_TOKEN="$BODY"
          echo "Authentication successful"

      - name: Fetch secret
        run: |
          RAW_PATH=data%2Fvault%2Fconjurtest%2Fmysecret%2Fpassword
          SECRET_URL=$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/$RAW_PATH
          SECRET_RESPONSE=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Token token=\"$AUTHN_TOKEN\"" \
            "$SECRET_URL")
          SECRET_VALUE=$(echo "$SECRET_RESPONSE" | sed '$d')
          SECRET_STATUS=$(echo "$SECRET_RESPONSE" | tail -n1)
          if [ "$SECRET_STATUS" != "200" ]; then
            echo "Failed to fetch secret (status $SECRET_STATUS)"
            exit 1
          fi
          echo "Retrieved secret: $SECRET_VALUE"
